/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\IdeaProjects\\codesuger-booklet-vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-29d16f94",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29d16f94").then(next)
    },
  },
  {
    name: "v-09f7d2ca",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09f7d2ca").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-c66ccb58",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c66ccb58").then(next)
    },
  },
  {
    name: "v-0e1ddb52",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e1ddb52").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-4d76208b",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d76208b").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-24737316",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24737316").then(next)
    },
  },
  {
    name: "v-bd2252cc",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd2252cc").then(next)
    },
  },
  {
    name: "v-40eb3d4e",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40eb3d4e").then(next)
    },
  },
  {
    name: "v-b99e7fd4",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b99e7fd4").then(next)
    },
  },
  {
    name: "v-00aef094",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00aef094").then(next)
    },
  },
  {
    name: "v-2e2ee0d4",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e2ee0d4").then(next)
    },
  },
  {
    name: "v-2762fb94",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2762fb94").then(next)
    },
  },
  {
    name: "v-0c171076",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c171076").then(next)
    },
  },
  {
    name: "v-2667aa40",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2667aa40").then(next)
    },
  },
  {
    name: "v-004e8b84",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-004e8b84").then(next)
    },
  },
  {
    name: "v-294e770c",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-294e770c").then(next)
    },
  },
  {
    name: "v-939e4ac8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-939e4ac8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-e34b7f54",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e34b7f54").then(next)
    },
  },
  {
    name: "v-300887f6",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-300887f6").then(next)
    },
  },
  {
    name: "v-2a55de78",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a55de78").then(next)
    },
  },
  {
    name: "v-2b4c7216",
    path: "/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b4c7216").then(next)
    },
  },
  {
    name: "v-3cc3d441",
    path: "/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cc3d441").then(next)
    },
  },
  {
    path: "/notes/index.html",
    redirect: "/notes/"
  },
  {
    name: "v-d5f66a54",
    path: "/notes/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5f66a54").then(next)
    },
  },
  {
    name: "v-61a13796",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61a13796").then(next)
    },
  },
  {
    name: "v-2347e256",
    path: "/notes/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2347e256").then(next)
    },
  },
  {
    name: "v-3aeebd98",
    path: "/notes/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%92%8C%E6%95%B0%E5%AD%A6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3aeebd98").then(next)
    },
  },
  {
    path: "/notes/程序员和数学.html",
    redirect: "/notes/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%92%8C%E6%95%B0%E5%AD%A6.html"
  },
  {
    path: "/notes/程序员和数学.html",
    redirect: "/notes/%E7%A8%8B%E5%BA%8F%E5%91%98%E5%92%8C%E6%95%B0%E5%AD%A6.html"
  },
  {
    name: "v-253a4b0a",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-253a4b0a").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-04c1917c",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04c1917c").then(next)
    },
  },
  {
    name: "v-0574b130",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0574b130").then(next)
    },
  },
  {
    name: "v-a5a022da",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a5a022da").then(next)
    },
  },
  {
    name: "v-735f9383",
    path: "/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-735f9383").then(next)
    },
  },
  {
    name: "v-3f5d91fe",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f5d91fe").then(next)
    },
  },
  {
    name: "v-42e31883",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42e31883").then(next)
    },
  },
  {
    name: "v-15f167c3",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15f167c3").then(next)
    },
  },
  {
    name: "v-23e671fd",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23e671fd").then(next)
    },
  },
  {
    name: "v-09b06f5d",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09b06f5d").then(next)
    },
  },
  {
    name: "v-9aa82c42",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9aa82c42").then(next)
    },
  },
  {
    name: "v-49b0f55a",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49b0f55a").then(next)
    },
  },
  {
    name: "v-88e6897a",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-88e6897a").then(next)
    },
  },
  {
    name: "v-741a7960",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-741a7960").then(next)
    },
  },
  {
    name: "v-1946c1e0",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1946c1e0").then(next)
    },
  },
  {
    name: "v-475d7a50",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-475d7a50").then(next)
    },
  },
  {
    name: "v-5f4ff0ba",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f4ff0ba").then(next)
    },
  },
  {
    name: "v-30685831",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30685831").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-a7ce545c",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7ce545c").then(next)
    },
  },
  {
    name: "v-30116df2",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30116df2").then(next)
    },
  },
  {
    name: "v-7ff8f596",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ff8f596").then(next)
    },
  },
  {
    name: "v-7ac6d3d6",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ac6d3d6").then(next)
    },
  },
  {
    name: "v-25690956",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25690956").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]